algoritmo "Algoritmo - Comparação de números"

var
x,y: inteiro
inicio
escreval("Algoritmo - Comparação de números")
escreval
escreva("Digite o 1° número: ")
leia(x)
escreva("Digite o 2° número: ")
leia(y)
escreval
se ( x=y) entao
   escreva(x," é igual a ",y )
   senao
   se ( x > y) entao
         escreva(x," é maior que ",y )
         senao
         escreva(y," é maior que ",x )
   fimse
fimse
fimalgoritmo
