Algoritmo "Algoritmo - Números ímpares e múltiplos de 3 entre 1 e 500"

Var
i:inteiro
Inicio
escreval("Algoritmo - Números ímpares e múltiplos de 3 entre 1 e 500")
escreval
i <- 1
escreval(i)
para i de 1 ate 500 passo 2 faca
     se (i%3=0) entao
        escreval(i)
     fimse
fimpara

//2° FORMA
//i <- 1
//para i de 1 ate 500 passo 1 faca
//     se(i%2=1) entao
//               se(i%3=0) entao
//                         escreval(i)
//               fimse
//     fimse
//fimpara
Fimalgoritmo