Algoritmo "Exercícios"


Var
n1,n2,media: real

Inicio
 // ENTRADA
escreval("Média ponderada de duas notas")
escreval

escreva ("Digite a primeira nota:")
leia (n1)
escreval

escreva ("Digite a segunda nota:")
leia (n2)
escreval
                 
//PROCESSAMENTO
                 
media <- (n1*2 + n2*3)/ 5

//SAÍDA
                 
escreval ("A média ponderada das notas é:",media, " , com peso 2 para a primeira e peso 3 para a segunda")


Fimalgoritmo