Algoritmo "Exercício 23"

Var
a1,a2,a3: real

Inicio
escreval("Algoritmo - Terceiro ângulo do triângulo")
escreval

//ENTRADA
escreva("Digite a medida do primeiro ângulo do triângulo: ")
leia(a1)
escreva("Digite a medida do segundo ângulo do triângulo: ")
leia(a2)
//PROCESSAMENTO
a3 <- 180-a1-a2

//SAÍDA
escreval
escreval(" O terceiro ângulo do triângulo é: ",a3:3:2)





Fimalgoritmo