Algoritmo "Exercício 19"

Var
w,l,p: real

Inicio
escreval("Algoritmo - Potência para iluminar")
escreval

//ENTRADA
escreva("Digite a largura do cômodo em metros: ")
leia(l)
escreva("Digite a profundidade do cômodo em metros: ")
leia(p)

//PROCESSAMENTO
w <-l*p*18



//SAÍDA
escreval
escreval("A área do cômodo é: ",l*p," m²")
escreval ("A potência potência necessária para iluminar o cômodo é: ",w," W")




Fimalgoritmo