Algoritmo "Exercício 24"

Var
r,d,m,l: real

Inicio
escreval("Algoritmo - Conversão de dinheiro para viagem")
escreval

//ENTRADA
escreva("Digite a quantia em reais: ")
leia(r)
//PROCESSAMENTO
d <- r*1.8
m <- r*2.0
l <- r*1.57

//SAÍDA
escreval
escreval("A quantia em dólar é: ",d)
escreval("A quantia em marco alemão é: ",m)
escreval("A quantia em libra esterlina é: ",l)




Fimalgoritmo