Algoritmo "Exercício 9"

Var
a,bma,bme,h: real


Inicio
escreval("Algoritmo - Área do trapézio")
escreval

//ENTRADA
escreva("Digite o tamanho da base maior: ")
leia(bma)
escreva("Digite o tamanho da base menor: ")
leia(bme)
escreva("Digite o tamanho da altura: ")
leia(h)

//PROCESSAMENTO
a <- ((bma+bme)*h)/2

//SAÍDA
escreval
escreva("A área do trapézio é: ",a)

Fimalgoritmo