Algoritmo "Exercício 17"

Var
r,c,a,v: real

Inicio
escreval("Algoritmo - Volume, comprimento e área da esfera")
escreval

//ENTRADA
escreva("Digite o raio da esfera: ")
leia(r)

//PROCESSAMENTO
c <- 2*pi*r
a <- pi*r^2
v <- (3*pi*r^3)/4


//SAÍDA
escreval
escreval("Comprimento da esfera aproximadamente: ",c:4:2)
escreval("Área da esfera aproximadamente: ",a:4:2)
escreval("Volume da esfera aproximadamente: ",v:4:2)




Fimalgoritmo