Algoritmo "Exercício 20"

Var
h,d,res:real

Inicio
escreval("Algoritmo - Distância da escada")
escreval

//ENTRADA
escreva("Digite o ângulo da escada: ")
leia(h)
escreva("Digite a distância da escada até a parede: ")
leia(d)

//PROCESSAMENTO
res <- d/Tan(GraupRad(h))


//SAÍDA
escreval
escreval("A distância do chão da parede até a ponta de cima da escada é: ",res:7:2)





Fimalgoritmo