Algoritmo "Exercício 12"

Var
sm,sf,res: real

Inicio
escreval("Algoritmo - Quantidade de salários mínimos")
escreval

//ENTRADA
escreva("Digite o valor do salário mínimo: ")
leia(sm)
escreval
escreva("Digite o valor do salário do funcionário: ")
leia(sf)


//PROCESSAMENTO
res <- sf/sm

//SAÍDA
escreval
escreva("O funcionário recebe:",res:7:2," salários mínimos")


Fimalgoritmo