Algoritmo "Exercício 02"

Var
n1,n2,n3,res: inteiro

Inicio
escreval("Algoritmo - Multiplicação de números")
escreval
//ENTRADA
escreva("Digite o primeiro número: ")
leia(n1)
escreval
escreva("Digite o segundo número : ")
leia(n2)
escreval
escreva("Digite o terceiro número : ")
leia(n3)
escreval

//PROCESSAMENTO
res <- n1 * n2 * n3


//SAÍDA
escreva(n1," x ",n2," x ",n3," = ",res)

Fimalgoritmo