Algoritmo "Exercício 3"

Var
n1,n2: inteiro

Inicio
escreval("Algoritmo - Menor número")
escreval

//ENTRADA
escreva("Digite o primeiro número: ")
leia(n1)
escreva("Digite o segundo número: ")
leia(n2)


//PROCESSAMENTO


//SAÍDA
se ( n1>n2) entao
   escreva(n2," é menor que ",n1)
fimse
se ( n2>n1) entao
   escreva(n1," é menor que ",n2)
fimse
se ( n1=n2) entao
   escreva(n2," é igual ",n1)
fimse



Fimalgoritmo