Algoritmo "Algoritmo - Números entre 30 e 90"
Var
i,cont,j:inteiro

Inicio
escreval("Algoritmo - Números entre 30 e 90")
escreval
i <- 1
cont <- 0
para i de 1 ate 10 passo 1 faca
     escreva("Digite o",i,"° número: ")
     leia(j)
     se (j>30) e (j<90) entao
        cont <- cont + 1
     fimse
fimpara

//SAÍDA
escreval
escreval("Há",cont," números entre 30 e 90")



Fimalgoritmo