Algoritmo "Algoritmo - Delta - aula 4"
Var
a,b,c,delta:real

Inicio
//ENTRADAS
escreval("Algoritmo - Delta")
escreval
escreva("Digite o valor do coeficiente 'a': ")
leia(a)
escreval
escreva("Digite o valor do coeficiente 'b': ")
leia(b)
escreval
escreva("Digite o valor do coeficiente 'c': ")
leia(c)
escreval

//PROCESSAMENTO
delta <- b^2 - 4*a*c

//SAÍDA
escreval("O valor de delta é ",delta:4:1)



Fimalgoritmo