Algoritmo "Algoritmo_2 - Soma de dois inteiros"

Var

num1, num2, res: inteiro
Inicio

//ENTRADAS
escreval("Algoritmo de soma de dois números inteiros")
escreval

escreval("Digite o 1° número: ")

                 leia(num1)
                 
escreval("Digite o 2° número: ")

                 leia(num2)

//PROCESSAMENTO

res <- num1+num2

//SAÍDA

escreval ("A soma é igual a: ", res)
                 
Fimalgoritmo